export const INDUSTRIES = [
  "Advertising & Marketing",
  "Aerospace & Defense",
  "Agriculture",
  "Architecture & Design",
  "Automotive",
  "Banking & Finance",
  "Biotechnology",
  "Construction & Real Estate",
  "Consulting",
  "Consumer Goods",
  "Education",
  "Energy & Utilities",
  "Entertainment & Media",
  "Environmental Services",
  "Fashion & Apparel",
  "Food & Beverage",
  "Government & Public Sector",
  "Healthcare & Pharmaceuticals",
  "Hospitality & Travel",
  "Human Resources",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Non-Profit & NGO",
  "Retail & E-commerce",
  "Software & Technology",
  "Sports & Fitness",
  "Telecommunications",
  "Other",
] as const;
