import type { Express } from "express";
import authRouter from "./auth";
import authLogoutRouter from "./auth-logout";
import authPasswordRouter from "./auth-password";
import authVerifyEmailRouter from "./auth-verify-email";
import billingRouter from "./billing";
import plansRouter from "./plans";
import stripeRouter from "./stripe";
import usersRouter from "./users";
import linkedinRouter from "./users-linkedin";
import voiceLabRouter from "./voice-lab";
import contentRouter from "./content";
import postsRouter from "./posts";
import socialRouter from "./social";
import supportRouter from "./support";
import inboxRouter from "./inbox";
import linkedinConnectRouter from "./linkedin-connect";
import { linkedinWebhook } from "../controllers/linkedin-connect.controller";
import pipelinesRouter from "./pipelines";
import trendsRouter from "./trends";
import analyticsRouter from "./analytics";
import recyclerRouter from "./recycler";
import feedbackRouter from "./feedback";
import servicesRouter from "./services";
import socialNotificationsRouter from "./social-notifications";
import platformRouter from "./platform";
import avatarRouter from "./avatar";
import { mountAdminRoutes } from "./admin-index";
import { proxyImage } from "../controllers/image-proxy.controller";
import { authenticate } from "../middleware/auth";
import { healthReport } from "../lib/health-report";

export function mountApiRoutes(app: Express): void {
  app.get("/api/health", (_req, res) => { res.json(healthReport()); });
  app.get("/api/image-proxy", authenticate, proxyImage);
  app.use("/api/auth", authRouter);
  app.use("/api/auth", authLogoutRouter);
  app.use("/api/auth", authPasswordRouter);
  app.use("/api/auth", authVerifyEmailRouter);
  app.use("/api/billing", billingRouter);
  app.use("/api/plans", plansRouter);
  app.use("/api/stripe", stripeRouter);
  app.use("/api/users", usersRouter);
  app.use("/api/users/me/linkedin-pdf", linkedinRouter);
  app.use("/api/voice-lab", voiceLabRouter);
  app.use("/api/content", contentRouter);
  app.use("/api/posts", postsRouter);
  app.use("/api/social", socialRouter);
  app.use("/api/support", supportRouter);
  app.use("/api/inbox", inboxRouter);
  app.post("/api/linkedin/webhook", (req, res, next) => linkedinWebhook(req, res).catch(next));
  app.use("/api/linkedin", linkedinConnectRouter);
  app.use("/api/pipelines", pipelinesRouter);
  app.use("/api/trends", trendsRouter);
  app.use("/api/analytics", analyticsRouter);
  app.use("/api/recycler", recyclerRouter);
  app.use("/api/feedback", feedbackRouter);
  app.use("/api/services", servicesRouter);
  app.use("/api/social/notifications", socialNotificationsRouter);
  app.use("/api/platform", platformRouter);
  app.use("/api/avatar", avatarRouter);
  mountAdminRoutes(app);
}
