ALTER TABLE opportunities
  ADD COLUMN facebook_url  VARCHAR(2048) NULL DEFAULT NULL,
  ADD COLUMN instagram_url VARCHAR(2048) NULL DEFAULT NULL,
  ADD COLUMN x_url         VARCHAR(2048) NULL DEFAULT NULL,
  ADD COLUMN tiktok_url    VARCHAR(2048) NULL DEFAULT NULL,
  ADD COLUMN threads_url   VARCHAR(2048) NULL DEFAULT NULL;
