import type { BillingPlan } from "@/types/billing-plan";

export const BILLING_PLANS: readonly BillingPlan[] = [
  {
    id: "starter",
    name: "Free",
    price: "€0",
    cadence: "free forever",
    description: "Try the magic. No card needed.",
    features: [
      "5 AI posts / month",
      "2 AI images / month",
      "1 connected account",
      "Manual scheduling",
      "7-day post history",
    ],
  },
  {
    id: "pro",
    name: "Creator",
    price: "€29",
    cadence: "/month",
    description: "Everything a solo creator needs to ship consistently.",
    features: [
      "30 AI posts / month",
      "10 AI images / month",
      "3 connected accounts",
      "Voice training on your writing style",
      "Auto-scheduling & content calendar",
      "Basic analytics",
    ],
  },
  {
    id: "scale",
    name: "Business",
    price: "€79",
    cadence: "/month",
    description: "For multi-brand operators and small teams.",
    features: [
      "150 AI posts / month",
      "40 AI images / month",
      "Unlimited accounts — all 8 platforms",
      "DM inbox & comment replies",
      "Optimal-slot auto-scheduling",
      "Team seats (up to 3) & approvals",
      "Advanced analytics",
      "Priority support",
    ],
    highlighted: true,
    badge: "Most popular",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Custom",
    cadence: "pricing",
    description: "For agencies and large teams with custom needs.",
    cta: "contact",
    contactHref: "mailto:sales@linka.studio",
    features: [
      "Unlimited posts & images",
      "Unlimited team seats",
      "SSO & role-based access",
      "Audit logs & data export",
      "Dedicated account manager",
      "Custom SLA & onboarding",
    ],
  },
];
